name: gpu_env
channels:
  - lukepfister
  - anaconda
  - defaults
dependencies:
  - _tflow_190_select=0.0.1=gpu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.5.0=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.12=h23475e2_2
  - grpcio=1.12.1=py36hdbcaa40_0
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h211956c_0
  - intel-openmp=2019.0=118
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=habf39ab_1
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.0.5=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py36_0
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - pandas=0.23.4=py36h04863e7_0
  - pcre=8.42=h439df22_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=ha72d70b_1
  - protobuf=3.6.0=py36hf484d3e_0
  - py-opencv=3.4.2=py36hb342d67_1
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py36hfa4b5c9_1
  - setuptools=40.4.3=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.25.2=h7b6447c_0
  - tensorboard=1.9.0=py36hf484d3e_0
  - tensorflow=1.9.0=gpu_py36h02c5d5e_1
  - tensorflow-base=1.9.0=gpu_py36h6ecc378_0
  - tensorflow-gpu=1.9.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h96e3832_1
  - zlib=1.2.11=hfbfcf68_1
  - appdirs=1.4.3=py36h28b3542_0
  - certifi=2018.10.15=py36_0
  - decorator=4.3.0=py36_0
  - libopus=1.2.1=hb9ed12e_0
  - markupsafe=1.0=py36h14c3975_1
  - openssl=1.1.1=h7b6447c_0
  - python=3.6.7=h0371630_0
  - mako=1.0.4=py36_0
  - pycuda=2017.1=py36_0
  - pytools=2018.4=py36_0
  - pip:
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - cloudpickle==0.6.1
    - cmake==3.13.0
    - cycler==0.10.0
    - cython==0.29
    - dask==1.0.0
    - dlib==19.16.0
    - funcsigs==1.0.2
    - imutils==0.5.2
    - keras==2.2.4
    - kiwisolver==1.0.1
    - matplotlib==2.2.3
    - more-itertools==4.3.0
    - networkx==2.2
    - pluggy==0.8.0
    - py==1.7.0
    - pyparsing==2.2.2
    - pytest==4.0.0
    - pywavelets==1.0.1
    - reikna==0.7.2
    - scikit-image==0.14.1
    - scikit-learn==0.20.0
    - seaborn==0.9.0
    - toolz==0.9.0
prefix: /home/deez/anaconda3/envs/gpu_env

